name: cifra-k-backend

services:
  celery:
    build: .
    command: celery -A project worker --beat --loglevel=info
    container_name: cifra-k-backend-celery
    env_file: .env
    depends_on:
      django-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    image: cifra-k-backend-python
    restart: unless-stopped
    volumes:
      - ./.celery:/srv/celery
      - ./.media:/srv/media
      - ./app:/app

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: cifra-k-backend-django
    depends_on:
      django-init:
        condition: service_completed_successfully
    env_file: .env
    image: cifra-k-backend-python
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./.media:/srv/media
      - ./app:/app

  django-init:
    build: .
    command: sh -c "
        python manage.py migrate admin --noinput &&
        python manage.py migrate auth --noinput &&
        python manage.py migrate contenttypes --noinput &&
        python manage.py migrate sessions --noinput &&
        python manage.py createsuperuser --noinput || echo 'Superuser already exists.' &&
        python manage.py migrate app --noinput
      "
    container_name: cifra-k-backend-django-init
    depends_on:
      postgres-init:
        condition: service_completed_successfully
    env_file: .env
    image: cifra-k-backend-python
    volumes:
      - ./.media:/srv/media
      - ./app:/app

  postgres:
    container_name: cifra-k-backend-postgres
    env_file: .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql

  postgres-init:
    container_name: cifra-k-backend-postgres-init
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ "sh", "/.postgres/init.sh" ]
    env_file: .env
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    volumes:
      - ./.postgres:/.postgres

  redis:
    container_name: cifra-k-backend-redis
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: redis:8.4.0-alpine
    restart: unless-stopped

volumes:
  postgres:
    name: cifra-k-backend-postgres