name: cifra-k-backend

services:
  django:
    build: .
    command: > 
      sh -c "
        python manage.py migrate admin --noinput &&
        python manage.py migrate auth --noinput &&
        python manage.py migrate contenttypes --noinput &&
        python manage.py migrate sessions --noinput &&
        python manage.py createsuperuser --noinput || echo 'Superuser already exists.' &&
        python manage.py migrate app --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    container_name: cifra-k-backend-django
    depends_on:
      postgres-init:
        condition: service_completed_successfully
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./.media:/srv/media

  postgres:
    container_name: cifra-k-backend-postgres
    env_file: .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql

  postgres-init:
    container_name: cifra-k-backend-postgres-init
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ "sh", "/.postgres/init.sh" ]
    env_file: .env
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    volumes:
      - ./.postgres:/.postgres

volumes:
  postgres:
    name: cifra-k-postgres